version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: myca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_NAME: myca
    restart: always
    ports:
      - 8080:8080